### create new project
Post http://localhost:3000/project/create/
Authorization: Bearer {{$dotenv TOKEN}}
Content-Type: application/json

{
    "title": "first project title",
    "text": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Egestas purus viverra accumsan in nisl nisi."
}