### get user profile
http://localhost:3000/user/profile/
Authorization: Bearer {{$dotenv TOKEN}}

### edit user Profile
Post http://localhost:3000/user/profile/
Authorization: Bearer {{$dotenv TOKEN}}
Content-Type: application/json

{
    "first_name": "mohammadreza",
    "last_name": "karimi",
    "Skills": ""
}